# Generated by Django 5.2 on 2025-04-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudget',
            name='month',
            field=models.DateField(help_text='Use the first day of the month, e.g., 2025-04-01'),
        ),
    ]
